"""The data dictionary's contract tables match the contract (make contract renders them)."""

import importlib.util
from pathlib import Path

import yaml

ROOT = Path(__file__).parents[1]
spec = importlib.util.spec_from_file_location("dictionary", ROOT / "scripts/contract/dictionary.py")
dictionary = importlib.util.module_from_spec(spec)
spec.loader.exec_module(dictionary)  # type: ignore[union-attr]

CONTRACT = yaml.safe_load((ROOT / "contracts/edits.odcs.yaml").read_text())


def test_dictionary_tables_match_the_contract() -> None:
    text = (ROOT / "docs/data-dictionary.md").read_text()
    assert dictionary.render(text, CONTRACT) == text, "run 'make contract'"


def test_every_contract_schema_has_a_table_in_the_dictionary() -> None:
    text = (ROOT / "docs/data-dictionary.md").read_text()
    for schema in CONTRACT["schema"]:
        assert f"<!-- contract:{schema['name']} generated by make contract" in text


def test_a_table_is_rendered_from_the_contract() -> None:
    schema = {
        "properties": [
            {"name": "a", "physicalType": "string", "required": True, "primaryKey": True},
            {"name": "b", "physicalType": "bigint", "description": "Two\n  lines."},
        ]
    }
    assert dictionary.field_table(schema).splitlines()[2:] == [
        "| a | string | yes | PK |  |",
        "| b | bigint | no |  | Two lines. |",
    ]
