"""Render the contract's field tables into docs/data-dictionary.md.

Usage: python scripts/contract/dictionary.py [--check]
Each table sits between markers naming its contract schema; everything outside the markers
(silver and gold tables, notes) is written by hand. --check exits 1 if the file would change.
"""

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).parents[2]
CONTRACT = ROOT / "contracts/edits.odcs.yaml"
DICTIONARY = ROOT / "docs/data-dictionary.md"
BLOCK = re.compile(
    r"(<!-- contract:(?P<schema>\w+) generated by make contract; do not edit -->\n)"
    r".*?"
    r"(<!-- /contract:(?P=schema) -->)",
    re.S,
)


def field_table(schema: dict) -> str:
    rows = ["| Field | Type | Required | Key | Meaning |", "| --- | --- | --- | --- | --- |"]
    for prop in schema["properties"]:
        meaning = " ".join((prop.get("description") or "").split())
        rows.append(
            f"| {prop['name']} | {prop['physicalType']} | "
            f"{'yes' if prop.get('required') else 'no'} | "
            f"{'PK' if prop.get('primaryKey') else ''} | {meaning} |"
        )
    return "\n".join(rows) + "\n"


def render(text: str, contract: dict) -> str:
    schemas = {s["name"]: s for s in contract["schema"]}

    def replace(match: re.Match[str]) -> str:
        return match.group(1) + field_table(schemas[match.group("schema")]) + match.group(3)

    return BLOCK.sub(replace, text)


def main() -> None:
    contract = yaml.safe_load(CONTRACT.read_text())
    old = DICTIONARY.read_text()
    new = render(old, contract)
    if "--check" in sys.argv:
        if new != old:
            sys.exit("docs/data-dictionary.md is out of date: run 'make contract'.")
        return
    DICTIONARY.write_text(new)


if __name__ == "__main__":
    main()
